# Generated by Django 6.0.4 on 2026-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalle', models.CharField(max_length=200)),
                ('monto', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalle', models.CharField(max_length=200)),
                ('monto', models.FloatField(default=0)),
            ],
        ),
    ]
