# Generated by Django 6.0.4 on 2026-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresos',
            name='categoria',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
